#!/bin/bash

base=$(dirname $0)
base=$(cd $base; pwd)

git --version >/dev/null 2>&1 || {
    echo 'No git found. Please install git.' >&2
    exit -1
}


# Setup zsh
ln -svf "$base/.zshrc" ~
ln -svf "$base/.p10k.zsh" ~


# Setup Neovim
if nvim --version >/dev/null 2>&1; then
    [ -f ~/.config/nvim/init.lua ] && [ ! ~/.config/nvim/init.lua -ef "$base/.confing/nvim/init.lua" ] && {
        echo 'Please remove ~/.config/nvim/init.lua first.'
        exit -1
    }

    [ ! -f ~/.config/nvim/init.lua ] && {
        mkdir -p ~/.config/nvim
        ln -sv "$base/.config/nvim/init.lua" ~/.config/nvim/init.lua
    }

    nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
else
    echo 'No Neovim found. Skip setup Neovim.' >&2
fi
